apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ld5q6bflm-go 
  janus-idp.io/tekton: ld5q6bflm-go
  backstage.io/kubernetes-id: ld5q6bflm-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ld5q6bflm-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  